trt = {"SS": ["NX", "γ", "xf"],
       "S": ["Akw", "DL", "GK", "Marf", "VI", "Dé", "Gw", "Re", "RiZE", "Exe"],
       "A": ["FV", "Ri", "SrX", "Zw", "D-6'", "Vse", "NvK", "St", "25", "いろはす",
             "たまげた", "Sun", "KSR", "MNG", "ともしび", "NR", "PAG", "Ap"],
       "B": ["AKA", "A'F", "AP", "Ar", "axr", "CoR", "Cra", "FtS", "IGS", "KGR",
             "Res", "SGT", "Sy", "w'nd", "XV", "おかし", "shy", "Nautilus", "Valkyrie",
             "Ctw", "LnP", "spitze", "7st", "MzE"],
       "C": ["Zx", "GzK", "Hw", "おれんじ", "As", "axe", "Cr", "Eins", "GTO", "HvG",
             "Amb", "iZoNe", "JxS", "Lostrame", "Lv", "Nv", "PK", "Rnm", "sf", "Cv",
             "¢ν", "SFH", "SH", "Type", "Xan", "Unis", "LDH", "FTL", "IsK", "KZS",
             "MtG", "Vortex", "WiNG", "アフロ", "Null", "Nu", "LD", "IGS", "LN", "φЯ"],
       "D": ["atelier", "LN", "OO", "Rw", "Pss", "RaZ", "AHW", "Ass", "Axis", "CAJ",
             "F4D", "Nst", "Rainbow", "Rs", "RzR", "strategy", "VL", "Zed", "ZR",
             "zzZ", "くだもの", "code", "CMJ", "DZW", "f's", "fx", "Gf", "Hab", "Rc",
             "Rø", "TRB", "Vernal", "YaQ", "360°", "花嫁", "CoX", "LsV", "怨ismGaming",
             "aristole", "étoile", "FrZ", "Caf", "Hrnk", "HLS", "Lsy", "HhI★", "U-7",
             "旧帝大", "HiG", "RsT", "Flower", "Vortex"],
       "E": ["CrN", "KMC", "MaT", "MD", "Nt", "UCN", "にゃんぱす", "Air", "DaV", "ET",
             "GN", "MKR", "RoV", "V'n", "らーめん", "BMz", "BY", "C'F", "elf", "FoN",
             "SBS", "DFF", "Gxy", "NFs", "Gyaos", "noir", "OP", "STD", "Spica", "LIT",
             "てぃあどろっぷ", "NRZ", "TIJ", "Tryve", "ty", "XcR", "XYZ", "MkG", "YSP",
             "あず", "サムライ", "Reg", "AgS", "BKN", "Bijou", "Dnh", "Ez","FrP",
             "KL", "Azu", "SqV", "MG", "Genesis", "Fun"],
       "F": ["BTM", "AJS", "ENJ", "Epp", "KH", "NGZ", "WM", "Cry", "GoG", "jewel", "KCh",
             "LaV", "LCS", "snα", "LxE", "PGS", "SMD", "AL", "DST", "FD",
             "Ofa", "TKY", "Hrm", "ky", "INU", "Mef", "MoR", "MuK", 'Mx0', "DMs",
             "naturally", "NC", "Niz", "noel", "Osn", "OML", "Pal", "Vrost", "μ's",
             "Sign", "SV", "SP", "two", "TuR", "USR", "ぬーぞく", "Vrost", "VX", "Zen",
             "iON", "ポインコ", "sig", "λ", "ATC"],
       "G": ["KFT", "Luminous", "Per", "RP", "SLQ", "XR", "6-R", "BP", "IZ", "Ash",
             "crescent", "DeG", "OC", "Level", "GrL", "dns", "Exp", "FKZ", "FJI", "Trl",
             "FMP", "KM", "LCP", "LPT", "EDN", "Luxo", "Ly", "Lr", "McP", "MYT", "RsK"
             "NKW", "on", "PVU", "RH", "PPK", "Sat", "Яiot", "Spring", "TKY",
             "KCH", "Viola", "PN", "UZT", "VtL", "WU", "みそしる", "med", "cp", "D&P",
             "a'x", "TKY", "Ls", "StN", "KaS", "MCB", "PHJ", "Glanz", "MtV", "Yw", "HhI☆",
             "Vel", "Lr", "みけねこ", "Astra", "ΣX"],
       "H": ["うどん", "CoP", "DFF", "Disney", "TEX", "EMT", "MS", "𝓒𝓱𝓵𝓽", "syu", "Bd", "AFC",
             "ALC", "BEY", "DRK", "Est", "EW", "GB", "IGi", "inc", "LEM", "LTC", "NGFC", "SCK",
             "PT", "QK", "Qz", "Roxane", "Rry", "Sla", "SPC", "CST", "WAM", "Whk", "εzK", "ごはん",
             "Xeno α", "ヘイホー", "NPB", "WEN", "Nexus", "Gc"]}

